# Generated by Django 3.1.14 on 2022-12-20 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Menu',
        ),
    ]
