# Generated by Django 3.1.14 on 2023-02-02 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0006_auto_20230113_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='address1',
            new_name='block',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='address2',
            new_name='room_number',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='city',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='state',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='zip_code',
        ),
    ]
