# Generated by Django 3.1.14 on 2023-02-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0007_auto_20230202_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='reg',
            field=models.CharField(default='', max_length=200),
        ),
    ]
