# Generated by Django 3.1.14 on 2023-02-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0008_orders_reg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='room_number',
            new_name='room_num',
        ),
    ]
