# Generated by Django 3.1.14 on 2023-02-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0009_auto_20230202_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='tod',
            field=models.TimeField(default=''),
        ),
    ]
