# Generated by Django 3.1.14 on 2023-02-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0013_auto_20230209_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='tod',
            field=models.TimeField(verbose_name='HH:MM'),
        ),
    ]
